### ISSUE TITLE
Add an option to gpdb env to list only

### ISSUE THREAD

**Issue by Zerpet** [pivotal-gss/go-gpdb#13]
When you run `gpdb env` it displays a list of GPDB instances installed and it prompts what instance you want to use.

We would like to have an option like `--list` to only lists all the environments installed, without promting which one to use.

**Comment by faisaltheparttimecoder** [comment]
added: https://github.com/pivotal-gss/go-gpdb/commit/59485f7c845722a3c6fe7aa0c9a572ea0f293927
