### ISSUE TITLE
GPDB install command accepts vague version numbers

### ISSUE THREAD

**Issue by Zerpet** [pivotal-gss/go-gpdb#15]
The commadn `gpdb install` does not perform validation on the input of `-v / --version` flag. This is fine if the user inputs garbage like `asifhasldfj`, but it might lead to unexpected behaviour for vague specifications like `6.0`.

Running `gpdb install -v 6.0` might match a file name `5.16.0`, which will install an undesired version. This behaviour will happen with `5.1`, as it can potentially match version `5.11.x`.

We can do a validation check using a regex to contain at least 3 numbers and 2 dots.

**Comment by Zerpet** [comment]
Addressed here e83ff5147fd71e098b65ebf5fc18ee845e712250

**Comment by faisaltheparttimecoder** [comment]
master fix: https://github.com/pivotal-gss/go-gpdb/commit/cfd6629ad00eb31b4d4ef10bc699c017191d00dd
