### ISSUE TITLE
ssh error~

### ISSUE THREAD

**Issue by weirros** [pivotal-gss/go-gpdb#29]
INFO[2019-11-15 15:51:42] Downloading completed ....                   
INFO[2019-11-15 15:51:42] Downloaded file available at: src/gpdbinstall/download/greenplum-db-6.1.0-rhel7-x86_64.rpm 
INFO[2019-11-15 15:51:42] Installation the gpdb version 6.1.0, that was just downloaded 
INFO[2019-11-15 15:51:42] Running the installation for the product: gpdb 
INFO[2019-11-15 15:51:42] Found host file at location: /root/hostfile  
INFO[2019-11-15 15:51:42] Starting the program to install GPDB version: 6.1.0 
INFO[2019-11-15 15:51:42] Running precheck before installing the gpdb version: 6.1.0 
INFO[2019-11-15 15:51:42] Running Installation of gpdb version: 6.1.0  
INFO[2019-11-15 15:51:42] Found a rpm binary for the version 6.1.0: src/gpdbinstall/download/greenplum-db-6.1.0-rhel7-x86_64.rpm 
INFO[2019-11-15 15:51:42] Using the rpm file to install the GPDB Product: src/gpdbinstall/download/greenplum-db-6.1.0-rhel7-x86_64.rpm, this might take several minutes.... 
No Presto metadata available for base
No Presto metadata available for updates
INFO[2019-11-15 15:51:57] Setting up & Checking if the host is reachable 
INFO[2019-11-15 15:51:57] Running gpssh-exkeys to enable keyless access on this server 
INFO[2019-11-15 15:51:57] Setting up the ssh Copy ID for all the host(s) 
[ERROR]: Failed to ssh to localhost.localdomain. Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).

[ERROR]: Expected passwordless ssh to host localhost.localdomain
INFO[2019-11-15 15:52:00] Building and executing the gpinitsystem...   
INFO[2019-11-15 15:52:00] Searching & Generating the port to be used for database installation 
INFO[2019-11-15 15:52:00] Obtaining ports to be set for PRIMARY_PORT   
WARN[2019-11-15 15:52:00] Didn't find PRIMARY_PORT in the file, setting it to default value: 30000 
INFO[2019-11-15 15:52:00] Obtaining ports to be set for MASTER_PORT    
WARN[2019-11-15 15:52:00] Didn't find MASTER_PORT in the file, setting it to default value: 3000 
INFO[2019-11-15 15:52:00] Creating the gpinitsystem config file at: src/gpdbinstall/temp/gpinitsystemconfig_6.1.0_20191115155200 
INFO[2019-11-15 15:52:00] Finalizing the gpinitsystem for the single mode database installation 
INFO[2019-11-15 15:52:00] Stopping all the database running on this host, to free up semaphore for this installation 
INFO[2019-11-15 15:52:00] Cleaning up gpcc process is found any        
INFO[2019-11-15 15:52:00] All Postgres process are stopped on this server 
INFO[2019-11-15 15:52:00] Executing the gpinitsystem to initialize the database 
20191115:15:52:00:002016 gpinitsystem:localhost:root-[INFO]:-Checking configuration parameters, please wait...
20191115:15:52:00:002016 gpinitsystem:localhost:root-[FATAL]:-Unable to run this script as root Script Exiting!
FATA[2019-11-15 15:52:00] Failed while waiting for the command /usr/local/greenplum-db-6.1.0/bin/gpinitsystem err: exit status 2

**Comment by faisaltheparttimecoder** [comment]
Hello @weirros 

It seems like we cannot do `ssh localhost.localdomain`

```
[ERROR]: Failed to ssh to localhost.localdomain. Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).
[ERROR]: Expected passwordless ssh to host localhost.localdomain
```

Is this your own VM ? if yes what happens when you run `ssh localhost.localdomain` on  the terminal ? also can you paste the output from  `cat /etc/hosts`

Thanks

**Comment by faisaltheparttimecoder** [comment]
Hello @weirros , let us know if the steps mentioned here helps in your case (https://github.com/pivotal-gss/go-gpdb/blob/master/gpdb/INSTALL.md#troubleshooting)
