### ISSUE TITLE
Logging (Verbose and Debug)

### ISSUE THREAD

**Issue by brendanstephens** [pivotal-gss/go-gpdb#6]
If debug not set, let’s drop the file reference from logging. 
We can likely also drop the directory creation warning to keep the CLI clean and only log if there is an error by default.

**Comment by faisaltheparttimecoder** [comment]
> If debug not set, let’s drop the file reference from logging.

This is fixed: https://github.com/pivotal-gss/go-gpdb/commit/e3a6952de276337735dab3ddeb50c2de95bf47fa

@brendanstephens, do you want to add this feature 
> We can likely also drop the directory creation warning to keep the CLI clean and only log if there is an error by default.

**Comment by faisaltheparttimecoder** [comment]
nevermind @brendanstephens , that is also added: https://github.com/pivotal-gss/go-gpdb/commit/63bf06f34df842b555326c5408fa0dbb1931b2a5

Closing this issue

**Comment by faisaltheparttimecoder** [comment]
Found a bug and fixed

+ dropping of filename: https://github.com/pivotal-gss/go-gpdb/commit/888d5b1127c3fbbd6d9b90459a144a66073bda9b
+ removing warning on file creation: https://github.com/pivotal-gss/go-gpdb/commit/63bf06f34df842b555326c5408fa0dbb1931b2a5
