### ISSUE TITLE
gpdb install defaults

### ISSUE THREAD

**Issue by brendanstephens** [pivotal-gss/go-gpdb#8]
gpdb install (no options), should show available installs from downloads

**Comment by faisaltheparttimecoder** [comment]
Install from shows all the downloaded products: https://github.com/pivotal-gss/go-gpdb/commit/9469e31ce5942802676055a5078851d109900e1c which means "-v" is no longer a required parameter, but gpcc will still need the user to feed in manually.

Download now list all the downloaded products using the -l flag: https://github.com/pivotal-gss/go-gpdb/commit/15b9b12544ddb47b8971af23a4e96bcf7f22766e & https://github.com/pivotal-gss/go-gpdb/commit/4bc0b153b28399e687552555154b23c9da7bbb01

Closing as it is implemented
